# matugen-generated kitty theme
background #1a1110
foreground #f1dedc
cursor #ffb4ab
cursor_text_color #561e19
selection_background #ffb4ab
selection_foreground #561e19
url_color #e0c38c

color0 #1a1110
color1 #ffb4ab
color2 #e0c38c
color3 #e7bdb8
color4 #ffb4ab
color5 #584419
color6 #5d3f3c
color7 #f1dedc
color8 #a08c8a
color9 #93000a
color10 #e0c38c
color11 #e7bdb8
color12 #ffb4ab
color13 #584419
color14 #73332d
color15 #f1dedc

active_tab_background #ffb4ab
active_tab_foreground #561e19
inactive_tab_background #271d1c
inactive_tab_foreground #d8c2bf
active_border_color #ffb4ab
inactive_border_color #a08c8a
