[colors.primary]
background = '#131314'
foreground = '#e5e2e2'

[colors.cursor]
text = '#131314'
cursor = '#e5e2e2'

[colors.vi_mode_cursor]
text = '#131314'
cursor = '#c0c7d3'

[colors.search.matches]
foreground = '#45474b'
background = '#d3c1ce'

[colors.search.focused_match]
foreground = '#45474b'
background = '#c0c7d3'

[colors.footer_bar]
foreground = '#45474b'
background = '#e5e2e2'

[colors.hints.start]
foreground = '#45474b'
background = '#c5c6cc'

[colors.hints.end]
foreground = '#45474b'
background = '#c5c6cc'

[colors.selection]
text = '#c5c6cb'
background = '#45474b'


[colors.normal]
black   = '#45474b'
red     = '#ffb4ab'
green   = '#c0c7d3'
yellow  = '#c5c6cc'
blue    = '#d3c1ce'
magenta = '#c0c7d3'
cyan    = '#c5c6cc'
white   = '#e5e2e2'


[colors.bright]
black   = '#8f9196'
red     = '#ffb4ab'
green   = '#c0c7d3'
yellow  = '#c5c6cc'
blue    = '#d3c1ce'
magenta = '#c0c7d3'
cyan    = '#c5c6cc'
white   = '#e5e2e2'


[colors.dim]
black   = '#45474b'
red     = '#ffb4ab'
green   = '#c0c7d3'
yellow  = '#c5c6cc'
blue    = '#d3c1ce'
magenta = '#c0c7d3'
cyan    = '#c5c6cc'
white   = '#e5e2e2'
